service: aws-python-flask-api

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.8
  environment:
    PG_DATABASE: yairsggo
    PG_USER: yairsggo
    PG_HOST: rajje.db.elephantsql.com
    PG_PASS: MbuwvGgJcC-nXskeCQnhunp8C93XC2-p 

# export AWS_ACCESS_KEY_ID=AKIA5BN2AGXHMECNVN4I
# export AWS_SECRET_ACCESS_KEY=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
# export AWS_DEFAULT_REGION=us-east-1
# export PG_DATABASE=yairsggo
# export PG_USER=yairsggo
# export PG_HOST=rajje.db.elephantsql.com
# export PG_PASS=MbuwvGgJcC-nXskeCQnhunp8C93XC2-p 
functions:
  api:
    handler: wsgi_handler.handler
    # layers:
    #   - arn:aws:lambda:us-west-1:898466741470:layer:psycopg2-py38:1
    #   - arn:aws:lambda:ca-central-1:898466741470:layer:psycopg2-py38:1
    #   - arn:aws:lambda:us-east-1:898466741470:layer:psycopg2-py38:2
    #   - arn:aws:lambda:us-east-2:898466741470:layer:psycopg2-py38:1
    #   - arn:aws:lambda:us-west-1:898466741470:layer:psycopg2-py38:1
    #   - arn:aws:lambda:us-west-2:898466741470:layer:psycopg2-py38:1
    #   - arn:aws:lambda:eu-west-1:898466741470:layer:psycopg2-py38:1
    #   - arn:aws:lambda:eu-west-2:898466741470:layer:psycopg2-py38:1
    #   - arn:aws:lambda:eu-west-3:898466741470:layer:psycopg2-py38:1
    #   - arn:aws:lambda:eu-central-1:898466741470:layer:psycopg2-py38:1
    #   - arn:aws:lambda:eu-south-1:898466741470:layer:psycopg2-py38:1
    #   - arn:aws:lambda:ap-northeast-1:898466741470:layer:psycopg2-py38:1
    #   - arn:aws:lambda:ap-southeast-1:898466741470:layer:psycopg2-py38:1
    #   - arn:aws:lambda:ap-southeast-2:898466741470:layer:psycopg2-py38:1
    #   - arn:aws:lambda:sa-east-1:898466741470:layer:psycopg2-py38:1
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements




